version: "3"

# app - nome do servico
# ports - maps port 8000 from host to 8000 from image
# command - comando para executar a aplicação (0.0.0.0 - disponível para todos os ips do container)
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"